### ISSUE TITLE
No topics appearing on phpBB 3.3.13

### ISSUE THREAD

**Issue by jverkoey** [rmcgirr83/topfive#27]
When installed, I only see the following at the top of my home page:

<img width="1183" alt="Screenshot 2024-09-21 at 10 02 53 PM" src="https://github.com/user-attachments/assets/0cee20d5-389a-4332-a0ef-6065cff05a74">

**Comment by rmcgirr83** [comment]
That isn't this extension

**Comment by jverkoey** [comment]
Ah sorry!

**Comment by rmcgirr83** [comment]
Sorry that is this extension. You need to go  to the ACP and enable it in the extensions tab.

**Comment by jverkoey** [comment]
Hmm I did do that, but still the same result.

I'll leave it live on https://meta.cars.forum for a bit so you can see.

**Comment by jverkoey** [comment]
Oh! Facepalm. Sorry, I didn't actually enable it in the extensions tab. Why does the extension need to be enabled twice?

**Comment by rmcgirr83** [comment]
Is a rather oldish extension. I'm updating it currently so there will be a new version in a day or two.

**Comment by jverkoey** [comment]
Ah all good! Thank you for making this :) Will keep an eye out for the update!
